[package]
name = "aoc_23"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    ".",
    "core",
    "day_1a",
    "day_1b",
    "day_2a",
    "day_2b"
]

[dependencies]
core = { path = "core" }
day_1a = { path = "day_1a" }
day_1b = { path = "day_1b" }
day_2a = { path = "day_2a" }
day_2b = { path = "day_2b" }
